import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Thilak
 */
public class AddProducts extends javax.swing.JInternalFrame {
        Connection conn = null;

        String pro_name,category;
        String pro_id,b_price,s_price,qty;
        Statement stmt;
        ResultSet rs;
        
    public AddProducts() {
        initComponents();
        try{
            Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock_plant","root","");

            stmt = conn.createStatement();
        }catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        p6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        add = new javax.swing.JButton();
        p3 = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        show = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(22, 33));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Product ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 96, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Product Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Category");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Buying Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Selling Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 226, 38));
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 226, 44));
        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 226, 46));
        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 226, 43));
        getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 226, 46));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Category", "Buying price", "Selling price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 720, 753));

        add.setBackground(new java.awt.Color(255, 204, 51));
        add.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 129, 58));

        p3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        p3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plants", "Flowers", "Leaves", "Foliage", "Accessories" }));
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3ActionPerformed(evt);
            }
        });
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 226, 44));

        update.setBackground(new java.awt.Color(255, 204, 51));
        update.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 120, 58));

        delete.setBackground(new java.awt.Color(255, 204, 51));
        delete.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 129, 57));

        clear.setBackground(new java.awt.Color(255, 102, 0));
        clear.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 680, 120, 60));

        show.setBackground(new java.awt.Color(0, 204, 204));
        show.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        show.setText("View all");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 163, 60));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1600, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       try
        {
            String sqlQ = "delete from products where pro_id='" + p1.getText() + "';";
            stmt.executeUpdate(sqlQ);
            JOptionPane.showMessageDialog(null, "Data deleted!!");

        }catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       
        pro_id=p1.getText();
        pro_name=p2.getText();
        category=p3.getSelectedItem().toString();
        int b_price=Integer.parseInt(p4.getText());
        int s_price=Integer.parseInt(p5.getText());
        int qty=Integer.parseInt(p6.getText());
        
        

        try
        {
           String sqlQ = "insert into products values ('"+pro_id+"','"+ pro_name+"','"+ category+"','"+b_price+"','"+s_price+"','"+qty+"')";
            stmt.executeUpdate(sqlQ);
            JOptionPane.showMessageDialog(null, "Data sent!!");

        }catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
        
     
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
      
        try
        {
            String sqlQ = "update products set pro_id='" + p1.getText() + "',pro_name='" + p2.getText() + "',category='" + p3.getSelectedItem().toString() + "',b_price='" + p4.getText() + "',s_price='" + p5.getText() + "',qty='" + p6.getText() + "' where pro_id='" + p1.getText() + "';";
            stmt.executeUpdate(sqlQ);
            JOptionPane.showMessageDialog(null, "Data updated!!");

        }catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
    }//GEN-LAST:event_updateActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        try{
            String sqlQ = "select * from products";
            rs=stmt.executeQuery(sqlQ);

            while(rs.next())
            {
                pro_id=rs.getString("pro_id");
                pro_name=rs.getString("pro_name");
                category=rs.getString("category");
                b_price=String.valueOf(rs.getInt("b_price"));
                s_price=String.valueOf(rs.getInt("s_price"));
                qty=String.valueOf(rs.getInt("qty"));
                
                String tbData[] = {pro_id,pro_name,category,b_price,s_price,qty};
                DefaultTableModel tbl=(DefaultTableModel)jTable1.getModel();

                tbl.addRow(tbData);
            }

        }catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
    }//GEN-LAST:event_showActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        try{
            p1.setText("");
            p2.setText("");
            p4.setText("");
            p5.setText("");
            p6.setText("");

           
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
        }catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
    }//GEN-LAST:event_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JComboBox<String> p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JTextField p6;
    private javax.swing.JButton show;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
