import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class Register extends javax.swing.JFrame {
     Connection conn = null;

        String F_name,L_name,username,password ;
        Statement stmt;


    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
         try{
            Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock_plant","root","");

            stmt = conn.createStatement();
        }catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lt = new javax.swing.JTextField();
        ft = new javax.swing.JTextField();
        pwd = new javax.swing.JPasswordField();
        ur = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lt.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(lt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 496, 40));

        ft.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(ft, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 496, 37));

        pwd.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 384, 500, 40));

        ur.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(ur, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 306, 496, 40));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("First Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Last Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Username:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Password:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 110, -1));

        jLabel1.setFont(new java.awt.Font("Poor Richard", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Register");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 174, -1));

        jLabel6.setFont(new java.awt.Font("Poor Richard", 3, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Register");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 23, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/icons8-go-back-48.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 40, 40));

        jb2.setBackground(new java.awt.Color(255, 204, 51));
        jb2.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        jb2.setText("Register");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        jPanel2.add(jb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 158, 53));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 0, 720, 580));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/201fcf69dd62c8a929b974106c78dba8.jpg"))); // NOI18N
        jLabel7.setToolTipText("");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        F_name = ft.getText();
        L_name = lt.getText();
        username = ur.getText();
        password = pwd.getText();
        if (ft.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "The First name cannot be empty");
        }
        else if(lt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "The Last name cannot be empty");
        }
        
         else if(ur.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "The Username cannot be empty");
        }
         
          else if(pwd.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "The Password  cannot be empty");
        }
           
       
        else{
          try
        {
                String sqlQ = "insert into login values ('"+F_name+"','"+L_name+"','"+username+"','"+password+"')";
                stmt.executeUpdate(sqlQ);
                JOptionPane.showMessageDialog(null, "You are succesfully registered");
                this.setVisible(false);
                new login().setVisible(true); 
            
        }catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
    }//GEN-LAST:event_jb2ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        
       
                                          
            
         
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ft;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jb2;
    private javax.swing.JTextField lt;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JTextField ur;
    // End of variables declaration//GEN-END:variables
}
