
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;




/*
/**
 *
 * @author Thilak
 */
public class Sales extends javax.swing.JInternalFrame {
 Connection conn = null;
 Statement stmt;
 Connection con;
 PreparedStatement pst;
 ResultSet rs; 
 String pname_sale,category;
 String  pid_sale,amount_sale,price_sale,pqty_sale;

        
        
       public Sales() {
           
        initComponents();
         try{
            Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock_plant","root","");

            stmt = conn.createStatement();
        }catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpname = new javax.swing.JTextField();
        txtpcode = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        txtqty = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        txtotal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        txtbal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        setOpaque(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtpname.setBackground(new java.awt.Color(0, 102, 102));
        txtpname.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        txtpname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 267, 40));

        txtpcode.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        txtpcode.setForeground(new java.awt.Color(204, 0, 0));
        txtpcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpcodeActionPerformed(evt);
            }
        });
        txtpcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpcodeKeyPressed(evt);
            }
        });
        getContentPane().add(txtpcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 267, 41));

        txtprice.setBackground(new java.awt.Color(0, 102, 102));
        txtprice.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        txtprice.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 293, 267, 40));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setText("Product ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setText("Product Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel4.setText("Quantity:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jTable1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Qty", "Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 780, 380));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel5.setText("Total:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 120, 40));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel6.setText("Balance:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 780, 150, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 150, 50));

        jLabel9.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel9.setText("Price");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel10.setText("Pay:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 90, -1));

        txtpay.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        getContentPane().add(txtpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 280, 50));

        txtqty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtqtyStateChanged(evt);
            }
        });
        getContentPane().add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 80, 40));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel11.setText("Amount:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        txtamount.setBackground(new java.awt.Color(0, 102, 102));
        txtamount.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        txtamount.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 270, 40));

        txtotal.setBackground(new java.awt.Color(0, 102, 102));
        txtotal.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        txtotal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 280, 50));

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        jButton2.setText("Print Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, 140, 60));

        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtbill.setRows(5);
        jScrollPane2.setViewportView(txtbill);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, 400, 520));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbal.setBackground(new java.awt.Color(0, 102, 102));
        txtbal.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        txtbal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtbal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 770, 280, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("*Press enter after typing the ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 230, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Balance();
        bill();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtqtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtqtyStateChanged

        int qty = Integer.parseInt(txtqty.getValue().toString());
        int price = Integer.parseInt(txtprice.getText());

        int tot = qty * price;

        txtamount.setText(String.valueOf(tot));
    }//GEN-LAST:event_txtqtyStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pid_sale=txtpcode.getText();
        pname_sale=txtpname.getText();
 
        int pqty=Integer.parseInt(txtqty.getValue().toString());
        int price_sale=Integer.parseInt(txtprice.getText());
        int amount_sale=Integer.parseInt(txtamount.getText());
        
        

        try
        {
           String sqlQ = "insert into sales values ('"+pid_sale+"','"+ pname_sale+"','"+pqty+"','"+price_sale+"','"+amount_sale+"')";
            stmt.executeUpdate(sqlQ);
        

        }catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
        
        
        
        
        
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]

            {
                txtpcode.getText(),
                txtpname.getText(),
                txtqty.getValue().toString(),
                txtprice.getText(),
                txtamount.getText(),
            });

            int sum = 0;

            for(int i = 0; i<jTable1.getRowCount(); i++)
            {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 4).toString());
            }

            txtotal.setText(Integer.toString(sum));

            txtpcode.setText("");
            txtpname.setText("");
            txtprice.setText("");
            txtamount.setText("");
            txtpcode.requestFocus();
            
       
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtpcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpcodeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String pcode = txtpcode.getText();
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock_plant","root","");
                pst = con.prepareStatement("select * from products where pro_id = ?");
                pst.setString(1, pcode);
                rs = pst.executeQuery();

                if(rs.next() == false)
                {
                    JOptionPane.showMessageDialog(this, "Product Code Not Found");
                }
                else
                {
                    String pname = rs.getString("pro_name");
                    String price = rs.getString("s_price");
                    txtpname.setText(pname.trim());
                    txtprice.setText(price.trim());
                }
            } catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
        }
    }//GEN-LAST:event_txtpcodeKeyPressed

    private void txtpcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpcodeActionPerformed

    public void Balance(){
        
        int total = Integer.parseInt(txtotal.getText());
        int pay = Integer.parseInt(txtpay.getText());
        
        int bal = pay - total;
        
        txtbal.setText(String.valueOf(bal));
        
        
        
    }
     public void bill(){
         
         String total = txtotal.getText();
         String pay = txtpay.getText();
         String bal = txtbal.getText();
         
          DefaultTableModel model = new DefaultTableModel();
        
        model = (DefaultTableModel)jTable1.getModel();
         
         txtbill.setText(txtbill.getText() + "******************************************************\n");
         txtbill.setText(txtbill.getText() + "              SAMPATH NATURE PLANTS                    \n");
         txtbill.setText(txtbill.getText() + "*******************************************************\n");
         
         //Heading
          txtbill.setText(txtbill.getText() + "Product" + "\t" + "Price" + "\t" + "Amount" + "\n"  );
          
          
          for(int i = 0; i < model.getRowCount(); i++)
          {
              
              String pname = (String)model.getValueAt(i, 1);
              String price = (String)model.getValueAt(i, 3);
              String amount = (String)model.getValueAt(i, 4); 
              
           txtbill.setText(txtbill.getText() + pname  + "\t" + price + "\t" + amount  + "\n"  );
    
          }
          
          txtbill.setText(txtbill.getText() + "\n");     
          
          txtbill.setText(txtbill.getText() + "\t" + "\t" + "Subtotal :" + total + "\n");
          txtbill.setText(txtbill.getText() + "\t" + "\t" + "Pay :" + pay + "\n");
          txtbill.setText(txtbill.getText() + "\t" + "\t" + "Balance :" + bal + "\n");
          txtbill.setText(txtbill.getText() + "\n");
          txtbill.setText(txtbill.getText() + "*******************************************************\n");
          txtbill.setText(txtbill.getText() + "           THANK YOU COME AGAIN             \n");
          txtbill.setText(txtbill.getText() + "*******************************************************\n");
          txtbill.setText(txtbill.getText() + "*******************************************************\n");
           txtbill.setText(txtbill.getText() + "           WASH YOUR HANDS AND STAY SAFE             \n");
          txtbill.setText(txtbill.getText() + "*******************************************************\n");
         
     }
    
   
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtbal;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtotal;
    private javax.swing.JTextField txtpay;
    private javax.swing.JTextField txtpcode;
    private javax.swing.JTextField txtpname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JSpinner txtqty;
    // End of variables declaration//GEN-END:variables
}
