import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;





/**
 *
 * @author Thilak
 */
public class Stock extends javax.swing.JInternalFrame {
     Connection conn=null ;
     Statement stmt;
     ResultSet rs; 
     String pro_name,category;
     String  pro_id,s_price,b_price,qty;
     PreparedStatement pst;

        
    public Stock() {
        initComponents();
             try{
            Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock_plant","root","");

            stmt = conn.createStatement();
        }catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
           
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        st1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Category", "b_price", "s_price_", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 466, 1316, 481));

        jPanel3.setBackground(new java.awt.Color(0, 204, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                st1KeyPressed(evt);
            }
        });
        jPanel3.add(st1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 90, 50));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setText("Product Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel5.setText("Category");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel6.setText("Quantity");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 170, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        jButton2.setText("View All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 168, 52));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 168, 48));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setText("Enter Product ID");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 180, -1));

        j3.setFont(new java.awt.Font("Segoe Print", 3, 36)); // NOI18N
        j3.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 210, 133, 56));

        j1.setFont(new java.awt.Font("Segoe Print", 3, 36)); // NOI18N
        j1.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 510, 56));

        j2.setFont(new java.awt.Font("Segoe Print", 3, 36)); // NOI18N
        j2.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 215, 56));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("*Press enter after typing the ID");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 1390, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            j1.setText("");
            j2.setText("");
            j3.setText("");

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
        }catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            String sqlQ = "select * from products";
            rs=stmt.executeQuery(sqlQ);

            while(rs.next())
            {
                pro_id=rs.getString("pro_id");
                pro_name=rs.getString("pro_name");
                category=rs.getString("category");
                b_price=String.valueOf(rs.getInt("b_price"));
                s_price=String.valueOf(rs.getInt("s_price"));
                qty=String.valueOf(rs.getInt("qty"));

                String tbData[] = {pro_id,pro_name,category,b_price,s_price,qty};
                DefaultTableModel tbl=(DefaultTableModel)jTable1.getModel();

                tbl.addRow(tbData);
            }

        }catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void st1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_st1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String pcode = st1.getText();
            try {
                Class.forName("com.mysql.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock_plant","root","");
                pst = conn.prepareStatement("select * from products where pro_id = ?");
                pst.setString(1, pcode);
                rs = pst.executeQuery();

                if(rs.next() == false)
                {
                    JOptionPane.showMessageDialog(this, "Product Code Not Found");
                }
                else
                {

                    String pro_name = rs.getString("pro_name");
                    String category = rs.getString("category");
                    String qty = rs.getString("qty");
                    j1.setText(pro_name.trim());
                    j2.setText(category.trim());
                    j3.setText(qty.trim());
                }
            } catch(Exception ee){JOptionPane.showMessageDialog(null, ee.toString());}
        }
    }//GEN-LAST:event_st1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField st1;
    // End of variables declaration//GEN-END:variables
}
